//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.23 at 11:44:55 AM IST 
//


package com.soap.consumewsdl.amlock.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soap.consumewsdl.amlock.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Actionstatus_QNAME = new QName("http://ws.amlock.infotech.com/", "actionstatus");
    private final static QName _ActionstatusResponse_QNAME = new QName("http://ws.amlock.infotech.com/", "actionstatusResponse");
    private final static QName _OnBordingScanning_QNAME = new QName("http://ws.amlock.infotech.com/", "onBordingScanning");
    private final static QName _OnBordingScanningResponse_QNAME = new QName("http://ws.amlock.infotech.com/", "onBordingScanningResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soap.consumewsdl.amlock.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Actionstatus }
     * 
     */
    public Actionstatus createActionstatus() {
        return new Actionstatus();
    }

    /**
     * Create an instance of {@link ActionstatusResponse }
     * 
     */
    public ActionstatusResponse createActionstatusResponse() {
        return new ActionstatusResponse();
    }

    /**
     * Create an instance of {@link OnBordingScanning }
     * 
     */
    public OnBordingScanning createOnBordingScanning() {
        return new OnBordingScanning();
    }

    /**
     * Create an instance of {@link OnBordingScanningResponse }
     * 
     */
    public OnBordingScanningResponse createOnBordingScanningResponse() {
        return new OnBordingScanningResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Actionstatus }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Actionstatus }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.amlock.infotech.com/", name = "actionstatus")
    public JAXBElement<Actionstatus> createActionstatus(Actionstatus value) {
        return new JAXBElement<Actionstatus>(_Actionstatus_QNAME, Actionstatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionstatusResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActionstatusResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.amlock.infotech.com/", name = "actionstatusResponse")
    public JAXBElement<ActionstatusResponse> createActionstatusResponse(ActionstatusResponse value) {
        return new JAXBElement<ActionstatusResponse>(_ActionstatusResponse_QNAME, ActionstatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OnBordingScanning }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OnBordingScanning }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.amlock.infotech.com/", name = "onBordingScanning")
    public JAXBElement<OnBordingScanning> createOnBordingScanning(OnBordingScanning value) {
        return new JAXBElement<OnBordingScanning>(_OnBordingScanning_QNAME, OnBordingScanning.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OnBordingScanningResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OnBordingScanningResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://ws.amlock.infotech.com/", name = "onBordingScanningResponse")
    public JAXBElement<OnBordingScanningResponse> createOnBordingScanningResponse(OnBordingScanningResponse value) {
        return new JAXBElement<OnBordingScanningResponse>(_OnBordingScanningResponse_QNAME, OnBordingScanningResponse.class, null, value);
    }

}
